### ISSUE TITLE
Привет 👋

### ISSUE THREAD

**Issue by soul-wish** [D-Pushkarevskiy/Gallery#1]
По поводу твоей работы: ты не мог бы выложить оригинальные файлы (например рядом с минифицированными)? Очень трудно что-либо понять глядя на минифицированный код, надеюсь ты это понимаешь. Мне важно видеть весь код в том виде, в котором ты его написал: JS, CSS, HTML. И напиши каким образом ты минифицировал все файлы. Спасибо!

**Comment by D-Pushkarevskiy** [comment]
> По поводу твоей работы: ты не мог бы выложить оригинальные файлы (например рядом с минифицированными)? Очень трудно что-либо понять глядя на минифицированный код, надеюсь ты это понимаешь. Мне важно видеть весь код в том виде, в котором ты его написал: JS, CSS, HTML. И напиши каким образом ты минифицировал все файлы. Спасибо!

Добрый день.
Вылил файлы в полном размере.
CSS минифицировал с помощью онлайн сервиса, JS с помощью UglifyJS2.
